# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wxy2IcbIeYiIKBL5SNrmumSu0gDVLwvF
"""

!pip --q install boto3
!pip --q install pandas
!pip --q install psycopg2
!pip --q install pygeohash

import boto3
import pygeohash
import os
import pandas as pd

s3 = boto3.resource(
    's3',
    region_name = 'us-east-2',
    aws_access_key_id = 'AKIAX623ELTIDJXPDBSV',
    aws_secret_access_key = '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'
)

from io import StringIO

obj = s3.Object('dados-upe-reitoria', 'taxi.txt')
body = obj.get()['Body'].read().decode('utf-8')


#df = pd.read_csv(StringIO(body))

df = pd.read_csv(
    obj.get()['Body'],
    header=None,
    names=['car_id', 'timestamp', 'lon', 'lat']  # definindo nomes manualmente pois arquivo não tem header
)


print (body)

import pygeohash as pgh

df['geohash'] = df.apply(
    lambda row: pgh.encode(row['lat'], row['lon'], precision=6),
    axis=1
)

regiao_mais_carros = (
    df.groupby('geohash')['car_id']
    .nunique()
    .sort_values(ascending=False)
)

print("Região com mais carros:")
df['geohash'].value_counts()

from math import radians, cos, sin, asin, sqrt

def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # km
    dlat = radians(lat2 - lat1)
    dlon = radians(lon2 - lon1)
    a = sin(dlat/2)**2 + cos(radians(lat1)) * cos(radians(lat2)) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a))
    return R * c

df = df.sort_values(['car_id', 'timestamp'])

df['lat_prev'] = df.groupby('car_id')['lat'].shift(1)
df['lon_prev'] = df.groupby('car_id')['lon'].shift(1)

df['dist_km'] = df.apply(
    lambda row: haversine(row['lat_prev'], row['lon_prev'], row['lat'], row['lon'])
    if pd.notnull(row['lat_prev']) else 0,
    axis=1
)

movimento_por_carro = (
    df.groupby('car_id')['dist_km']
    .sum()
    .sort_values(ascending=False)
)

print("Carro que mais se movimentou:")
print(movimento_por_carro.head(1))

#TESTE

#codigo = pygeohash.encode(-7.9848983672628, -34.85448)
#print (codigo)